# Generated by Django 4.2.8 on 2023-12-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_basic_info_github_url_alter_basic_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='github_url',
            field=models.URLField(),
        ),
    ]
